at 00:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 01:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 02:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 03:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 04:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 05:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 06:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 07:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 08:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 09:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 10:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 11:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 12:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 13:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 14:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 15:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 16:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 17:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 18:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 19:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 20:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 21:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 22:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs
at 23:00 /every:M,T,W,Th,F,S,Su C:\vbs\alertMail.vbs